site_name: ConTeX
theme: readthedocs
nav:
        - index.md
        - license.md
        - installation.md
        - document-structure.md
        - configuration.md
        - slides.md
        - layout.md
        - math.md
        - table.md
        - drawings.md
        - fonts.md
        - languages.md
        - colors.md
        - bibliography.md
        - fine-tuning.md
        - programming-with-lua.md
        - command-reference.md
        - Appendix:
                - appendix/color-table.md
# extra_javascript:
#         - js/color/defs.js
#         - js/color/gen-table.js
# extra_css:
#         - css/color/color-table.css
