site_name: ConTeX
theme: readthedocs
nav:
        - index.md
        - license.md
        - installation.md
        - quick-start.md
        - layout.md
        - command-reference.md
        - Appendix:
                - appendix/color-table.md
extra_javascript:
        - js/color/defs.js
        - js/color/gen-table.js
